version: 0.0
os: windows
files:
  - source: ./maven-simplest-3.6.2-fat.jar
    destination: /tmp
  - source: ./java-start.bat
    destination: /tmp
hooks:
  ApplicationStart:
    - location: C:/tmp/java-start.bat
      runas: administrator
      timeout: 900