version: 0.0
os: linux
files:
  - source: maven-simplest-3.6.2-fat.jar
    destination: /opt/hello
  - source: java-start.sh
    destination: /opt/hello
  - source: java-stop.sh
    destination: /opt/hello 
permissions:    
  - object: /opt/hello
    pattern: "*.jar"
    owner: ec2-user
    group: ec2-user
  - object: /opt/hello
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  ApplicationStop:
    - location: ./java-stop.sh
      runas: root
      timeout: 900
  ApplicationStart:
    - location: ./java-start.sh
      runas: ec2-user
      timeout: 900