version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/maven-simplest-3.6.2-fat.jar
    - appspec.yml
  discard-paths: yes